[project]
name = "uvx-launcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet[all]>=0.28.3",
]

[project.scripts]
test = "src.test:print_message"
launcher = "src.launcher:run_launcher"
