[project]
name = "uvx-launcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flet[all]>=0.28.3",
]

[tool.uv]
package = false


[project.scripts]
test = "test:print_message"
launcher = "launcher:run_launcher"
